### ISSUE TITLE
Architectury v. 6.5.77 not compatible with create goggles

### ISSUE THREAD

**Issue by IchePlayer** [Robocraft999/CreateGoggles#2]
With following error:

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Architectury' (architectury) 6.5.77 with version 6.2.43.
Unmet dependency listing:
	 - Mod 'Create Goggles' (creategoggles) 0.5.4 requires version 6.2.43 of mod 'Architectury' (architectury), but only the wrong version is present: 6.5.77!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Robocraft999** [comment]
ok. I fix it. should be ready in the next days
