### ISSUE TITLE
Server Crash on Startup 1.18.2

### ISSUE THREAD

**Issue by PikaCrew** [Robocraft999/CreateGoggles#27]
This problem pops up only when launching from server. Modpack launches just fine on client side.

06.12 15:16:33 [Server] INFO -- MOD creategoggles --
06.12 15:16:33 [Server] INFO Details:
06.12 15:16:33 [Server] INFO Mod File: /mods/creategoggles-0.5.5.c-[FORGE].jar
06.12 15:16:33 [Server] INFO Failure message: Create Goggles (creategoggles) encountered an error during the common_setup event phase
06.12 15:16:33 [Server] INFO java.lang.ClassCastException: class com.robocraft999.creategoggles.item.modifier.ItemModifier cannot be cast to class net.minecraftforge.registries.IForgeRegistryEntry (com.robocraft999.creategoggles.item.modifier.ItemModifier is in module creategoggles@0.5.5.c of loader 'TRANSFORMER' @6481dce5; net.minecraftforge.registries.IForgeRegistryEntry is in module forge@40.2.14 of loader 'TRANSFORMER' @6481dce5)
06.12 15:16:33 [Server] INFO Mod Version: 0.5.5.c
06.12 15:16:33 [Server] INFO Mod Issue URL: https://github.com/Robocraft999/CreateGoggles/issues
06.12 15:16:33 [Server] INFO Exception message: java.lang.ClassCastException: class com.robocraft999.creategoggles.item.modifier.ItemModifier cannot be cast to class net.minecraftforge.registries.IForgeRegistryEntry (com.robocraft999.creategoggles.item.modifier.ItemModifier is in module creategoggles@0.5.5.c of loader 'TRANSFORMER' @6481dce5; net.minecraftforge.registries.IForgeRegistryEntry is in module forge@40.2.14 of loader 'TRANSFORMER' @6481dce5)
06.12 15:16:33 [Server] INFO Stacktrace:
06.12 15:16:33 [Server] INFO at dev.architectury.registry.registries.forge.RegistriesImpl$ForgeBackedRegistryImpl.lambda$register$2(RegistriesImpl.java:588) ~[architectury-4.11.93-forge.jar%2349!/:?] {re:classloading}
06.12 15:16:33 [Server] INFO at dev.architectury.registry.registries.forge.RegistriesImpl$RegistryProviderImpl$EventListener.handleEvent(RegistriesImpl.java:274) ~[architectury-4.11.93-forge.jar%2349!/:?] {re:classloading}
06.12 15:16:33 [Server] INFO at net.minecraftforge.eventbus.ASMEventHandler_31_EventListener_handleEvent_Register.invoke(.dynamic) ~[?:?] {}
06.12 15:16:33 [Server] INFO at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
06.12 15:16:33 [Server] INFO at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
06.12 15:16:33 [Server] INFO at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
06.12 15:16:33 [Server] INFO at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106) ~[javafmllanguage-1.18.2-40.2.14.jar%23255!/:?] {}
06.12 15:16:33 [Server] INFO at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:122) ~[fmlcore-1.18.2-40.2.14.jar%23254!/:?] {}
06.12 15:16:33 [Server] INFO at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
06.12 15:16:33 [Server] INFO at net.minecraftforge.fml.ModWorkManager$SyncExecutor.driveOne(ModWorkManager.java:42) ~[fmlcore-1.18.2-40.2.14.jar%23254!/:?] {}
06.12 15:16:33 [Server] INFO at net.minecraftforge.fml.ModWorkManager$DrivenExecutor.drive(ModWorkManager.java:26) ~[fmlcore-1.18.2-40.2.14.jar%23254!/:?] {}
06.12 15:16:33 [Server] INFO at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:202) ~[fmlcore-1.18.2-40.2.14.jar%23254!/:?] {}
06.12 15:16:33 [Server] INFO at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$21(ModLoader.java:187) ~[fmlcore-1.18.2-40.2.14.jar%23254!/:?] {}
06.12 15:16:33 [Server] INFO at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
06.12 15:16:33 [Server] INFO at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:187) ~[fmlcore-1.18.2-40.2.14.jar%23254!/:?] {}
06.12 15:16:33 [Server] INFO at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$11(ModLoader.java:164) ~[fmlcore-1.18.2-40.2.14.jar%23254!/:?] {}
06.12 15:16:33 [Server] INFO at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
06.12 15:16:33 [Server] INFO at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:164) ~[fmlcore-1.18.2-40.2.14.jar%23254!/:?] {}
06.12 15:16:33 [Server] INFO at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:32) ~[forge-1.18.2-40.2.14-universal.jar%23258!/:?] {re:classloading}
06.12 15:16:33 [Server] INFO at net.minecraft.server.Main.main(Main.java:112) ~[server-1.18.2-20220404.173914-srg.jar%23253!/:?] {re:classloading,re:mixin,pl:mixin:A}
06.12 15:16:33 [Server] INFO at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
06.12 15:16:33 [Server] INFO at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
06.12 15:16:33 [Server] INFO at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
06.12 15:16:33 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
06.12 15:16:33 [Server] INFO at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:32) ~[fmlloader-1.18.2-40.2.14.jar%2318!/:?] {}
06.12 15:16:33 [Server] INFO at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
06.12 15:16:33 [Server] INFO at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
06.12 15:16:33 [Server] INFO at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
06.12 15:16:33 [Server] INFO at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
06.12 15:16:33 [Server] INFO at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
06.12 15:16:33 [Server] INFO at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
06.12 15:16:33 [Server] INFO at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
06.12 15:16:33 [Server] INFO at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

**Comment by Beafty** [comment]
same here:
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Suspected Mod:
        Architectury (architectury), Version: 4.11.93
                Issue tracker URL: https://github.com/shedaniel/architectury/issues
                at TRANSFORMER/architectury@4.11.93/dev.architectury.registry.registries.forge.RegistriesImpl$ForgeBackedRegistryImpl.lambda$register$2(RegistriesImpl.java:588)
Stacktrace:
        at dev.architectury.registry.registries.forge.RegistriesImpl$ForgeBackedRegistryImpl.lambda$register$2(RegistriesImpl.java:588) ~[architectury-4.11.93-forge.jar%2343!/:?] {re:classloading}
-- MOD creategoggles --
Details:
        Mod File: /F:/1.18.2server/mods/creategoggles-0.5.5.c-[FORGE].jar
        Failure message: Create Goggles (creategoggles) encountered an error during the common_setup event phase
                java.lang.ClassCastException: class com.robocraft999.creategoggles.item.modifier.ItemModifier cannot be cast to class net.minecraftforge.registries.IForgeRegistryEntry (com.robocraft999.creategoggles.item.modifier.ItemModifier is in module creategoggles@0.5.5.c of loader 'TRANSFORMER' @3cc053; net.minecraftforge.registries.IForgeRegistryEntry is in module forge@40.2.17 of loader 'TRANSFORMER' @3cc053)
        Mod Version: 0.5.5.c
        Mod Issue URL: https://github.com/Robocraft999/CreateGoggles/issues
        Exception message: java.lang.ClassCastException: class com.robocraft999.creategoggles.item.modifier.ItemModifier cannot be cast to class net.minecraftforge.registries.IForgeRegistryEntry (com.robocraft999.creategoggles.item.modifier.ItemModifier is in module creategoggles@0.5.5.c of loader 'TRANSFORMER' @3cc053; net.minecraftforge.registries.IForgeRegistryEntry is in module forge@40.2.17 of loader 'TRANSFORMER' @3cc053)
Stacktrace:
        at dev.architectury.registry.registries.forge.RegistriesImpl$ForgeBackedRegistryImpl.lambda$register$2(RegistriesImpl.java:588) ~[architectury-4.11.93-forge.jar%2343!/:?] {re:classloading}
        at dev.architectury.registry.registries.forge.RegistriesImpl$RegistryProviderImpl$EventListener.handleEvent(RegistriesImpl.java:274) ~[architectury-4.11.93-forge.jar%2343!/:?] {re:classloading}
        at net.minecraftforge.eventbus.ASMEventHandler_153_EventListener_handleEvent_Register.invoke(.dynamic) ~[?:?] {}
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
        at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106) ~[javafmllanguage-1.18.2-40.2.17.jar%23102!/:?] {}
        at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:123) ~[fmlcore-1.18.2-40.2.17.jar%23101!/:?] {}
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
        at net.minecraftforge.fml.ModWorkManager$SyncExecutor.driveOne(ModWorkManager.java:42) ~[fmlcore-1.18.2-40.2.17.jar%23101!/:?] {}
        at net.minecraftforge.fml.ModWorkManager$DrivenExecutor.drive(ModWorkManager.java:26) ~[fmlcore-1.18.2-40.2.17.jar%23101!/:?] {}
        at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:202) ~[fmlcore-1.18.2-40.2.17.jar%23101!/:?] {}
        at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$21(ModLoader.java:187) ~[fmlcore-1.18.2-40.2.17.jar%23101!/:?] {}
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
        at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:187) ~[fmlcore-1.18.2-40.2.17.jar%23101!/:?] {}
        at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$11(ModLoader.java:164) ~[fmlcore-1.18.2-40.2.17.jar%23101!/:?] {}
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
        at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:164) ~[fmlcore-1.18.2-40.2.17.jar%23101!/:?] {}
        at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:32) ~[forge-1.18.2-40.2.17-universal.jar%23105!/:?] {re:classloading}
        at net.minecraft.server.Main.main(Main.java:112) ~[server-1.18.2-20220404.173914-srg.jar%23100!/:?] {re:classloading,re:mixin,pl:mixin:A}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
        at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:32) ~[fmlloader-1.18.2-40.2.17.jar%2318!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

**Comment by Robocraft999** [comment]
I found out why. Thanks for reporting guys. I fix it the next days. (I'm dumb and have some mixin that should be on both sides only registered on client side)

**Comment by Robocraft999** [comment]
should be fixed now
