### ISSUE TITLE
game crashes when looking at recipe for diamond jetpack in emi 1.20.1 

### ISSUE THREAD

**Issue by MaddyMarv** [Robocraft999/CreateGoggles#39]
i tried upgrading EMI and downgrading it with no luck, I also removed all the addons for it. if you could help that wpuld be great, thank you!

crash log:
-- Head --
Thread: Render thread
Suspected Mod: 
	EMI (emi), Version: 1.1.13+1.20.1+forge
		at TRANSFORMER/emi@1.1.13+1.20.1+forge/dev.emi.emi.jemi.JemiRecipeHandler.createSlotsView(JemiRecipeHandler.java:187)
Stacktrace:
	at java.util.AbstractList.subListRangeCheck(AbstractList.java:507) ~[?:?] {re:mixin}
	at java.util.ArrayList.subList(ArrayList.java:1108) ~[?:?] {re:mixin}
	at dev.emi.emi.jemi.JemiRecipeHandler.createSlotsView(JemiRecipeHandler.java:187) ~[emi-1.1.13+1.20.1+forge.jar%23768!/:?] {re:classloading}
	at dev.emi.emi.jemi.JemiRecipeHandler.render(JemiRecipeHandler.java:88) ~[emi-1.1.13+1.20.1+forge.jar%23768!/:?] {re:classloading}
	at dev.emi.emi.screen.RecipeScreen.m_88315_(RecipeScreen.java:238) ~[emi-1.1.13+1.20.1+forge.jar%23768!/:?] {re:classloading}
	at net.minecraft.client.gui.screens.Screen.m_280264_(Screen.java:109) ~[client-1.20.1-20230612.114412-srg.jar%231044!/:?] {re:computing_frames,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fabric-screen-api-v1.mixins.json:ScreenMixin from mod fabric_screen_api_v1,pl:mixin:APP:yungsmenutweaks.mixins.json:ScreenMixin from mod yungsmenutweaks,pl:mixin:APP:cumulus_menus.mixins.json:client.accessor.ScreenAccessor from mod cumulus_menus,pl:mixin:APP:mixins.essential.json:client.gui.GuiScreen

**Comment by Robocraft999** [comment]
Can't confim. Are you sure the item you're looking for is from this mod? We don't have jetpacks here and it works fine with the backtanks for me
